# Normal Hours
IV = {'MONDAY': [7, '00', 22, '00'],
      'TUESDAY': [7, '00', 22, '00'],
      'WEDNESDAY': [7, '00', 22, '00'],
      'THURSDAY': [7, '00', 22, '00'],
      'FRIDAY': [7, '00', 21, '00'],
      'WEEKENDS': [8, '00', 21, '00'],
      'LINK': 'https://nudining.com/hours'}
STEAST = {'MONDAY': [7, '00', 23, '00'],
          'TUESDAY': [7, '00', 23, '00'],
          'WEDNESDAY': [7, '00', 23, '00'],
          'THURSDAY': [7, '00', 23, '00'],
          'FRIDAY': [7, '00', 22, '00'],
          'WEEKENDS': [8, '00', 22, '00'],
          'LINK': 'https://nudining.com/hours'}
STWEST = {'MONDAY': [11, '00', 20, '00'],
          'TUESDAY': [11, '00', 20, '00'],
          'WEDNESDAY': [11, '00', 20, '00'],
          'THURSDAY': [11, '00', 20, '00'],
          'FRIDAY': [11, '00', 17, '00'],
          'SATURDAY': "CLOSED",
          'SUNDAY': [16, '00', 20, '00'],
          'LINK': 'https://nudining.com/hours'}
OUTTAKES = {'MONDAY': [11, '00', 25, '00'],
            'TUESDAY': [11, '00', 25, '00'],
            'WEDNESDAY': [11, '00', 25, '00'],
            'THURSDAY': [11, '00', 25, '00'],
            'FRIDAY': [11, '00', 20, '00'],
            'SATURDAY': [12, '00', 18, '00'],
            'SUNDAY': "CLOSED",
            'LINK': 'https://nudining.com/hours'}
ARGO_TEA = {'MONDAY': [7, '30', 20, '00'],
            'TUESDAY': [7, '30', 20, '00'],
            'WEDNESDAY': [7, '30', 20, '00'],
            'THURSDAY': [7, '30', 20, '00'],
            'FRIDAY': [7, '30', 17, '00'],
            'SATURDAY': "CLOSED",
            'SUNDAY': [13, '00', 20, '00'],
            'LINK': 'https://nudining.com/hours'}
CAFE_CROSSING = {'MONDAY': [7, '00', 17, '00'],
                 'TUESDAY': [7, '00', 17, '00'],
                 'WEDNESDAY': [7, '00', 17, '00'],
                 'THURSDAY': [7, '00', 17, '00'],
                 'FRIDAY': [7, '00', 16, '00'],
                 'WEEKENDS': "CLOSED",
                 'LINK': 'https://nudining.com/hours'}
CAFE_716 = {'MONDAY': [7, '00', 16, '00'],
            'TUESDAY': [7, '00', 16, '00'],
            'WEDNESDAY': [7, '00', 16, '00'],
            'THURSDAY': [7, '00', 16, '00'],
            'FRIDAY': [7, '00', 15, '00'],
            'WEEKENDS': "CLOSED",
            'LINK': 'https://nudining.com/hours'}
FACULTY_CLUB = {'WEEKDAYS': [11, '30', 14, '00'],
                'WEEKENDS': "CLOSED",
                'LINK': 'https://nudining.com/hours'}
KIGO = {'MONDAY': [11, '00', 19, '00'],
        'TUESDAY': [11, '00', 19, '00'],
        'WEDNESDAY': [11, '00', 19, '00'],
        'THURSDAY': [11, '00', 19, '00'],
        'FRIDAY': [11, '00', 16, '00'],
        'WEEKENDS': "CLOSED",
        'LINK': 'https://nudining.com/hours'}
POPEYES = {'WEEKDAYS': [10, '30', 21, '00'],
           'SATURDAY': [10, '30', 20, '00'],
           'SUNDAY': [12, '00',  19, '00'],
           'LINK': 'https://nudining.com/hours'}
REBECCAS = {'WEEKDAYS': [7, '00', 16, '00'],
            'WEEKENDS': "CLOSED",
            'LINK': 'https://nudining.com/hours'}
STARBUCKS = {'WEEKDAYS': [7, '00', 21, '00'],
             'SATURDAY': [8, '00', 21, '00'],
             'SUNDAY': [10, '00',  18, '00'],
             'LINK': 'https://nudining.com/hours'}
SUBWAY = {'MONDAY': [8, '00', 16, '30'],
          'TUESDAY': [8, '00', 16, '30'],
          'WEDNESDAY': [8, '00', 16, '30'],
          'THURSDAY': [8, '00', 16, '30'],
          'FRIDAY': [11, '00', 16, '00'],
          'WEEKENDS': "CLOSED",
          'LINK': 'https://nudining.com/hours'}
SWEET_TOMATOES = {'MONDAY': [11, '00', 19, '00'],
                  'TUESDAY': [11, '00', 19, '00'],
                  'WEDNESDAY': [11, '00', 19, '00'],
                  'THURSDAY': [11, '00', 19, '00'],
                  'FRIDAY': [11, '00', 18, '00'],
                  'WEEKENDS': "CLOSED",
                  'LINK': 'https://nudining.com/hours'}
THE_MARKET = {'MONDAY': [7, '00', 22, '00'],
              'TUESDAY': [7, '00', 22, '00'],
              'WEDNESDAY': [7, '00', 22, '00'],
              'THURSDAY': [7, '00', 22, '00'],
              'FRIDAY': [7, '00', 21, '30'],
              'SATURDAY': [9, '00', 21, '00'],
              'SUNDAY': [11, '00', 21, '00'],
              'LINK': 'https://nudining.com/hours'}
THE_WEST_END = {'MONDAY': [11, '00', 19, '00'],
                'TUESDAY': [11, '00', 19, '00'],
                'WEDNESDAY': [11, '00', 19, '00'],
                'THURSDAY': [11, '00', 19, '00'],
                'FRIDAY': [11, '00', 15, '30'],
                'WEEKENDS': "CLOSED",
                'LINK': 'https://nudining.com/hours'}
UBURGER = {'WEEKDAYS': [11, '00', 20, '00'],
           'SATURDAY': [11, '00', 19, '00'],
           'SUNDAY': [12, '00', 19, '00'],
           'LINK': 'https://nudining.com/hours'}
ZATAR = {'MONDAY': [11, '00', 19, '00'],
         'TUESDAY': [11, '00', 19, '00'],
         'WEDNESDAY': [11, '00', 19, '00'],
         'THURSDAY': [11, '00', 19, '00'],
         'FRIDAY': [11, '00', 15, '30'],
         'WEEKENDS': "CLOSED",
         'LINK': 'https://nudining.com/hours'}
QDOBA = {'MONDAY': [10, '30', 23, '00'],
         'TUESDAY': [10, '30', 23, '00'],
         'WEDNESDAY': [10, '30', 23, '00'],
         'THURSDAY': [10, '30', 24, '00'],
         'FRIDAY': [10, '30', 24, '00'],
         'SATURDAY': [10, '30', 24, '00'],
         'SUNDAY': [10, '30', 22, '00'],
         'LINK': 'https://locations.qdoba.com/us/ma/boston/393-huntington-ave.html'}
AMELIAS = {'MONDAY': [7, '00', 23, '00'],
           'TUESDAY': [7, '00', 23, '00'],
           'WEDNESDAY': [7, '00', 23, '00'],
           'THURSDAY': [7, '00', 23, '00'],
           'FRIDAY': [7, '00', 26, '00'],
           'SATURDAY': [7, '00', 26, '00'],
           'SUNDAY': [7, '30', 22, '00'],
           'LINK': 'https://ameliastaqueria.com/locations/huntington-ave/'}
BOSTON_SHAWARMA = {'EVERYDAY': [10, '00', 23, '30'],
                   'LINK': 'http://www.bostonshawarma.net'}
CAPPYS = {'EVERYDAY': [6, '30', 26, '00'],
          'LINK': 'http://cappyspizza.com/indexs.php'}
CHICKEN_LOUS = {'MONDAY': [6, '45', 16, '30'],
                'TUESDAY': [6, '45', 16, '30'],
                'WEDNESDAY': [6, '45', 16, '30'],
                'THURSDAY': [6, '45', 16, '30'],
                'FRIDAY': [6, '45', 18, '45'],
                'SATURDAY': [7, '30', 14, '30'],
                'SUNDAY': "CLOSED",
                'LINK': 'https://www.chickenlous.com'}
COLLEGE_CONVENIENCE = {'EVERYDAY': [0, '00', 24, '00'],
                       'LINK': 'https://menupages.com/college-convenience/281-huntington-ave-boston/#about'}
CVS = {"EVERYDAY": [7, '00', 24, '00'],
       'LINK': 'https://www.cvs.com/store-locator/cvs-pharmacy-address/231+Massachusetts+Avenue-Boston-MA-02115/storeid=1259'}
DOMINOS = {"EVERYDAY": [10, '30', 27, '00'],
           'LINK': 'https://pizza.dominos.com/massachusetts/boston/1260-boylston-st/'}
RESMAIL = {'WEEKDAYS': [8, '00', 20, '00'],
           'SATURDAY': [10, '00', 16, '00'],
           'SUNDAY': "CLOSED",
           'LINK': 'http://www.northeastern.edu/mailservices/ResMail/ResMail.html'}
GYROSCOPE = {'EVERYDAY': [11, '00', 23, '00'],
             'LINK': 'https://www.gyroscopeboston.com'}
PANERA = {'EVERYDAY': [6, '00', 22, '00'],
          'LINK': 'https://www.panerabread.com/en-us/home.html'}
PHO_I = {'MONDAY': [11, '30', 22, '00'],
         'TUESDAY': [11, '30', 22, '00'],
         'WEDNESDAY': [11, '30', 22, '00'],
         'THURSDAY': [11, '30', 22, '00'],
         'FRIDAY': [11, '30', 22, '30'],
         'SATURDAY': [11, '30', 22, '30'],
         'SUNDAY': [11, '30', 22, '00'],
         'LINK': 'http://www.phoandi.com/Directions.html'}
STAR_MARKET = {'EVERYDAY': [6, '00', 24, '00'],
               'LINK': 'https://www.starmarket.com/#1'}
SYMPHONY_MARKET = {'EVERYDAY': [6, '00', 26, '00'],
                   'LINK': 'https://maps.apple.com/place?address=291%20Huntington%20Ave%2C%20Boston%2C%20MA%20%2002115%2C%20United%20States&auid=17122051796147320805&ll=42.34151398927978%2C-71.08679643398375&q=Symphony%20Market'}
UHOP = {'EVERYDAY': [11, '00', 25, '00'],
        'LINK': 'http://www.bostonuhop.com'}
WHOLE_FOODS = {'EVERYDAY': [7, '00', 10, '30'],
               'LINK': 'https://www.wholefoodsmarket.com/stores/symphony'}
WINGS_OVER = {'MONDAY': [16, '00', 24, '00'],
              'TUESDAY': [16, '00', 24, '00'],
              'WEDNESDAY': [11, '00', 24, '00'],
              'THURSDAY': [11, '00', 22, '00'],
              'FRIDAY': [11, '00', 26, '00'],
              'SATURDAY': [11, '00', 26, '00'],
              'SUNDAY': [11, '00', 24, '00'],
              'LINK': 'https://wingsover.com/locations/wings-over-boston'}
WOLLASTONS = {'MONDAY': [7, '00', 25, '00'],
              'TUESDAY': [7, '00', 25, '00'],
              'WEDNESDAY': [7, '00', 25, '00'],
              'THURSDAY': [7, '00', 25, '00'],
              'FRIDAY': [7, '00', 24, '00'],
              'SATURDAY': [7, '00', 24, '00'],
              'SUNDAY': [7, '00', 25, '00'],
              'LINK': 'https://wollastons-market.business.site'}
WOLLASTONS_WV = {'WEEKDAYS': [6, '00', 24, '00'],
                 'SATURDAY': [6, '00', 24, '00'],
                 'SUNDAY': [7, '00', 24, '00'],
                 'LINK': 'https://i.imgur.com/C6sCnuJ.png'}

#  Dictionary of locations & aliases for normal hours
NORMAL_LOCATIONS = {('INTERNATIONAL VILLAGE', 'IV'): IV, ('STETSON EAST', 'STEAST', 'STETSON E'): STEAST,
                    ('STETSON WEST', 'STWEST', 'STETSON W'): STWEST, ('OUTTAKES', 'OUTTAKES'): OUTTAKES,
                    ('ARGO TEA', 'ARGO'): ARGO_TEA, ('CAFÉ 716', 'CAFE 716'): CAFE_716,
                    ('CAFÉ CROSSING', 'CAFE CROSSING', 'CAFE CROSS'): CAFE_CROSSING,
                    ('FACULTY CLUB', 'FACULTY CLUB'): FACULTY_CLUB, ('KIGO KITCHEN', 'KIGO', 'KIGOS'): KIGO,
                    ('THE MARKET', 'MARKET'): THE_MARKET,
                    ('POPEYES LOUISIANA KITCHEN', 'POPEYES KITCHEN', 'POPEYES'): POPEYES,
                    ("REBECCA'S", 'REBECCAS'): REBECCAS, ('STARBUCKS', 'STARBUCKS'): STARBUCKS,
                    ('SUBWAY', 'SUBWAY'): SUBWAY, ('SWEET TOMATOES', 'SWEET TOMATOES'): SWEET_TOMATOES,
                    ('THE WEST END', 'WEST END'): THE_WEST_END, ('UBURGER', 'UBURGERS'): UBURGER,
                    ("ZA'TAR", 'ZATAR'): ZATAR, ('QDOBA', 'QDOBA'): QDOBA,
                    ("AMELIA'S TAQUERIA", "AMELIA'S", 'AMELIAS'): AMELIAS,
                    ('BOSTON SHAWARMA', 'SHAWARMA'): BOSTON_SHAWARMA, ("CAPPY'S", 'CAPPYS'): CAPPYS,
                    ("CHICKEN LOU'S", "CHICKEN LOUS", 'CHICKEN_LOUS', 'CL'): CHICKEN_LOUS,
                    ('COLLEGE CONVENIENCE', 'COLLEGE_CONVENIENCE', 'CC'): COLLEGE_CONVENIENCE,
                    ('CVS', 'CVS'): CVS, ('DOMINOS', 'DOMINOS'): DOMINOS, ('RESMAIL', 'RESMAIL'): RESMAIL,
                    ('GYROSCOPE', 'GYRO',): GYROSCOPE, ('PANERA BREAD', 'PANERA'): PANERA,
                    ('PHO AND I', 'PHO', 'PHO I', 'PHO & I'): PHO_I, ('STAR MARKET', 'STAR'): STAR_MARKET,
                    ('SYMPHONY MARKET', 'SYMPHONY'): SYMPHONY_MARKET,
                    ('UNIVERSITY HOUSE OF PIZZA', 'UHOP', 'UNIV PIZZA'): UHOP,
                    ('WHOLE FOODS', 'WHOLE FOODS'): WHOLE_FOODS, ('WINGS OVER', 'WINGS'): WINGS_OVER,
                    ("WOLLASTON'S MARKET", "WOLLASTON'S", 'WOLLASTONS', 'WOLLYS', "WOLLY'S", "WOLLASTON"): WOLLASTONS,
                    ("WOLLASTON'S MARKET WEST VILLAGE", "WOLLASTON'S WEST VILLAGE", 'WOLLASTONS WEST VILLAGE',
                     'WOLLYS WEST VILLAGE', "WOLLY'S WEST VILLAGE", "WOLLASTON'S MARKET WV", "WOLLASTON'S WV",
                     'WOLLASTONS WV', 'WOLLYS WV', "WOLLY'S WV", "WOLLASTON WV"): WOLLASTONS_WV}
POSSIBLE_LOCATIONS = ("International Village, Stetson East, Stetson West, Outtakes, Argo Tea, "
                      "Café 716, Café Crossing, Faculty Club, Kigo's Kitchen, The Market, Popeyes, "
                      "Rebecca's, Starbucks, Subway, Sweet Tomatoes, The West End, UBurger, Za'tar, "
                      "Qdoba, Amelia's Taqueria, Boston Shawarma, Cappy's, Chicken Lou's, "
                      " College Convenience, CVS, Dominos, Resmail, Gyroscope, Panera Bread, Pho and I, "
                      "Star Market, Symphony Market, University House of Pizza, Whole Foods, Wings Over, "
                      "Wollaston's Market, Wollaston's Market West Village")

# ice-cream flavors
ICE_CREAM_FLAVORS = {'MONDAY': 'STRAWBERRY & CHOCOLATE 🍨',
                     'TUESDAY': 'RASPBERRY CHOCOLATE & VANILLA 🍨',
                     'WEDNESDAY': 'VANILLA & MINT CHOCOLATE 🍨',
                     'THURSDAY': 'ORANGE CREAM & VANILLA 🍨',
                     'FRIDAY': 'MOCHA & VANILLA 🍨',
                     'SATURDAY': 'CHOCOLATE & COCONUT PINEAPPLE(Vanilla)🍨',
                     'SUNDAY': 'VANILLA & MAPLE 🍨'}

# Martin Luther King Weekend hours
IV_MLK = {'FRIDAY': [7, '00', 21, '00'],
          'SATURDAY': [8, '00', 20, '00'],
          'SUNDAY': [8, '00', 20, '00'],
          'MONDAY': [8, '00', 22, '00'],
          'LINK': 'https://nudining.com/hours'}
STEAST_MLK = {'FRIDAY': [7, '00', 21, '00'],
              'SATURDAY': [8, '00', 20, '00'],
              'SUNDAY': [8, '00', 20, '00'],
              'MONDAY': [8, '00', 23, '00'],
              'LINK': 'https://nudining.com/hours'}
STWEST_MLK = {'FRIDAY': [11, '00', 15, '00'],
              'SATURDAY': 'CLOSED',
              'SUNDAY': 'CLOSED',
              'MONDAY': [16, '00', 20, '00'],
              'LINK': 'https://nudining.com/hours'}
OUTTAKES_MLK = {'FRIDAY': [11, '00', 19, '00'],
                'SATURDAY': 'CLOSED',
                'SUNDAY': 'CLOSED',
                'MONDAY': 'CLOSED',
                'LINK': 'https://nudining.com/hours'}
ARGO_TEA_MLK = {'FRIDAY': [7, '30', 17, '00'],
                'SATURDAY': 'CLOSED',
                'SUNDAY': 'CLOSED',
                'MONDAY': 'CLOSED',
                'LINK': 'https://nudining.com/hours'}
CAFE_716_MLK = {'FRIDAY': [7, '00', 15, '00'],
                'SATURDAY': 'CLOSED',
                'SUNDAY': 'CLOSED',
                'MONDAY': 'CLOSED',
                'LINK': 'https://nudining.com/hours'}
CAFE_CROSSING_MLK = {'FRIDAY': [7, '00', 16, '00'],
                     'SATURDAY': 'CLOSED',
                     'SUNDAY': 'CLOSED',
                     'MONDAY': 'CLOSED',
                     'LINK': 'https://nudining.com/hours'}
FACULTY_CLUB_MLK = {'FRIDAY': [11, '30', 14, '00'],
                    'SATURDAY': 'CLOSED',
                    'SUNDAY': 'CLOSED',
                    'MONDAY': 'CLOSED',
                    'LINK': 'https://nudining.com/hours'}
KIGO_MLK = {'FRIDAY': [11, '00', 15, '00'],
            'SATURDAY': 'CLOSED',
            'SUNDAY': 'CLOSED',
            'MONDAY': 'CLOSED',
            'LINK': 'https://nudining.com/hours'}
THE_MARKET_MLK = {'FRIDAY': [7, '00', 21, '30'],
                  'SATURDAY': [9, '00', 21, '00'],
                  'SUNDAY': [11, '00', 20, '00'],
                  'MONDAY': [9, '00', 21, '00'],
                  'LINK': 'https://nudining.com/hours'}
POPEYES_MLK = {'FRIDAY': [10, '30', 20, '00'],
               'SATURDAY': [11, '30', 19, '00'],
               'SUNDAY': [12, '00', 18, '00'],
               'MONDAY': [11, '30', 20, '00'],
               'LINK': 'https://nudining.com/hours'}
REBECCAS_MLK = {'FRIDAY': [7, '00', 16, '00'],
                'SATURDAY': 'CLOSED',
                'SUNDAY': 'CLOSED',
                'MONDAY': [7, '00', 14, '00'],
                'LINK': 'https://nudining.com/hours'}
STARBUCKS_MLK = {'FRIDAY': [7, '00', 21, '00'],
                 'SATURDAY': [10, '30', 21, '00'],
                 'SUNDAY': [11, '00', 18, '00'],
                 'MONDAY': [10, '30', 9, '00'],
                 'LINK': 'https://nudining.com/hours'}
SUBWAY_MLK = {'FRIDAY': [8, '00', 16, '00'],
              'SATURDAY': 'CLOSED',
              'SUNDAY': 'CLOSED',
              'MONDAY': 'CLOSED',
              'LINK': 'https://nudining.com/hours'}
SWEET_TOMATOES_MLK = {'FRIDAY': [11, '00', 18, '00'],
                      'SATURDAY': 'CLOSED',
                      'SUNDAY': 'CLOSED',
                      'MONDAY': 'CLOSED',
                      'LINK': 'https://nudining.com/hours'}
THE_WEST_END_MLK = {'FRIDAY': [11, '00', 15, '00'],
                    'SATURDAY': 'CLOSED',
                    'SUNDAY': 'CLOSED',
                    'MONDAY': 'CLOSED',
                    'LINK': 'https://nudining.com/hours'}
UBURGER_MLK = {'FRIDAY': [11, '00', 20, '00'],
               'SATURDAY': 'CLOSED',
               'SUNDAY': 'CLOSED',
               'MONDAY': [11, '30', 19, '00'],
               'LINK': 'https://nudining.com/hours'}
ZATAR_MLK = {'FRIDAY': [11, '00', 15, '00'],
             'SATURDAY': 'CLOSED',
             'SUNDAY': 'CLOSED',
             'MONDAY': 'CLOSED',
             'LINK': 'https://nudining.com/hours'}

#  Dictionary of locations & aliases for MLK hours
MLK_LOCATIONS = {('INTERNATIONAL VILLAGE', 'IV'): IV_MLK, ('STETSON EAST', 'STEAST', 'STETSON E'): STEAST_MLK,
                 ('STETSON WEST', 'STWEST', 'STETSON W'): STWEST_MLK, ('OUTTAKES', 'OUTTAKES'): OUTTAKES_MLK,
                 ('ARGO TEA', 'ARGO'): ARGO_TEA_MLK, ('CAFÉ 716', 'CAFE 716'): CAFE_716_MLK,
                 ('CAFÉ CROSSING', 'CAFE CROSSING', 'CAFE CROSS'): CAFE_CROSSING_MLK,
                 ('FACULTY CLUB', 'FACULTY CLUB'): FACULTY_CLUB_MLK, ('KIGO KITCHEN', 'KIGO', 'KIGOS'): KIGO_MLK,
                 ('THE MARKET', 'MARKET'): THE_MARKET_MLK,
                 ('POPEYES LOUISIANA KITCHEN', 'POPEYES KITCHEN', 'POPEYES'): POPEYES_MLK,
                 ("REBECCA'S", 'REBECCAS'): REBECCAS_MLK, ('STARBUCKS', 'STARBUCKS'): STARBUCKS_MLK,
                 ('SUBWAY', 'SUBWAY'): SUBWAY_MLK, ('SWEET TOMATOES', 'SWEET TOMATOES'): SWEET_TOMATOES_MLK,
                 ('THE WEST END', 'WEST END'): THE_WEST_END_MLK, ('UBURGER', 'UBURGERS'): UBURGER_MLK,
                 ("ZA'TAR", 'ZATAR'): ZATAR_MLK}

# President's Weekend hours
IV_PRESIDENTS = IV_MLK
STEAST_PRESIDENTS = STEAST_MLK
STWEST_PRESIDENTS = STWEST_MLK
OUTTAKES_PRESIDENTS = OUTTAKES_MLK
ARGO_TEA_PRESIDENTS = ARGO_TEA_MLK
CAFE_716_PRESIDENTS = CAFE_716_MLK
CAFE_CROSSING_PRESIDENTS = CAFE_CROSSING_MLK
FACULTY_CLUB_PRESIDENTS = FACULTY_CLUB_MLK
KIGO_PRESIDENTS = KIGO_MLK
THE_MARKET_PRESIDENTS = THE_MARKET_MLK
POPEYES_PRESIDENTS = POPEYES_MLK
REBECCAS_PRESIDENTS = REBECCAS_MLK
STARBUCKS_PRESIDENTS = STARBUCKS_MLK
SUBWAY_PRESIDENTS = SUBWAY_MLK
SWEET_TOMATOES_PRESIDENTS = SWEET_TOMATOES_MLK
THE_WEST_END_PRESIDENTS = THE_WEST_END_MLK
UBURGER_PRESIDENTS = UBURGER_MLK
ZATAR_PRESIDENTS = ZATAR_MLK

#  Dictionary of locations and aliases for president's weekend hours
PRESIDENTS_LOCATIONS = {('INTERNATIONAL VILLAGE', 'IV'): IV_PRESIDENTS, ('STETSON EAST', 'STEAST', 'STETSON E'): STEAST_PRESIDENTS,
                        ('STETSON WEST', 'STWEST', 'STETSON W'): STWEST_PRESIDENTS, ('OUTTAKES', 'OUTTAKES'): OUTTAKES_PRESIDENTS,
                        ('ARGO TEA', 'ARGO'): ARGO_TEA_PRESIDENTS, ('CAFÉ 716', 'CAFE 716'): CAFE_716_PRESIDENTS,
                        ('CAFÉ CROSSING', 'CAFE CROSSING', 'CAFE CROSS'): CAFE_CROSSING_PRESIDENTS,
                        ('FACULTY CLUB', 'FACULTY CLUB'): FACULTY_CLUB_PRESIDENTS, ('KIGO KITCHEN', 'KIGO', 'KIGOS'): KIGO_PRESIDENTS,
                        ('THE MARKET', 'MARKET'): THE_MARKET_PRESIDENTS,
                        ('POPEYES LOUISIANA KITCHEN', 'POPEYES KITCHEN', 'POPEYES'): POPEYES_PRESIDENTS,
                        ("REBECCA'S", 'REBECCAS'): REBECCAS_PRESIDENTS, ('STARBUCKS', 'STARBUCKS'): STARBUCKS_PRESIDENTS,
                        ('SUBWAY', 'SUBWAY'): SUBWAY_PRESIDENTS, ('SWEET TOMATOES', 'SWEET TOMATOES'): SWEET_TOMATOES_PRESIDENTS,
                        ('THE WEST END', 'WEST END'): THE_WEST_END_PRESIDENTS, ('UBURGER', 'UBURGERS'): UBURGER_PRESIDENTS,
                        ("ZA'TAR", 'ZATAR'): ZATAR_PRESIDENTS}

# Spring Break 2019 Hours (March 1-10, 2019)
IV_SPRING_BREAK = {'FRIDAY': [7, '00', 16, '00'],
                   'SATURDAY': 'CLOSED',
                   'SUNDAY': 'CLOSED',
                   'MONDAY-THURSDAY': 'CLOSED',
                   'FRIDAY2': 'CLOSED',
                   'SATURDAY2': 'CLOSED',
                   'SUNDAY2': [12, '00', 21, '00'],
                   'LINK': 'https://nudining.com/hours'}
STEAST_SPRING_BREAK = {'FRIDAY': [7, '00', 22, '00'],
                       'SATURDAY': [8, '00', 20, '00'],
                       'SUNDAY': [8, '00', 20, '00'],
                       'MONDAY-THURSDAY': [7, '00', 20, '00'],
                       'FRIDAY2': [7, '00', 20, '00'],
                       'SATURDAY2': [8, '00', 20, '00'],
                       'SUNDAY2': [8, '00', 21, '00'],
                       'LINK': 'https://nudining.com/hours'}
STWEST_SPRING_BREAK = {'FRIDAY': [11, '00', 15, '00'],
                       'SATURDAY': 'CLOSED',
                       'SUNDAY': 'CLOSED',
                       'MONDAY-THURSDAY': 'CLOSED',
                       'FRIDAY2': 'CLOSED',
                       'SATURDAY2': 'CLOSED',
                       'SUNDAY2': 'CLOSED',
                       'LINK': 'https://nudining.com/hours'}
OUTTAKES_SPRING_BREAK = {'FRIDAY': [11, '00', 19, '00'],
                         'SATURDAY': 'CLOSED',
                         'SUNDAY': 'CLOSED',
                         'MONDAY-THURSDAY': 'CLOSED',
                         'FRIDAY2': 'CLOSED',
                         'SATURDAY2': 'CLOSED',
                         'SUNDAY2': 'CLOSED',
                         'LINK': 'https://nudining.com/hours'}
ARGO_TEA_SPRING_BREAK = {'FRIDAY': [7, '30', 15, '00'],
                         'SATURDAY': 'CLOSED',
                         'SUNDAY': 'CLOSED',
                         'MONDAY-THURSDAY': 'CLOSED',
                         'FRIDAY2': 'CLOSED',
                         'SATURDAY2': 'CLOSED',
                         'SUNDAY2': 'CLOSED',
                         'LINK': 'https://nudining.com/hours'}
CAFE_716_SPRING_BREAK = {'FRIDAY': [7, '00', 15, '00'],
                         'SATURDAY': 'CLOSED',
                         'SUNDAY': 'CLOSED',
                         'MONDAY-THURSDAY': [7, '00', 16, '00'],
                         'FRIDAY2': [7, '00', 15, '00'],
                         'SATURDAY2': 'CLOSED',
                         'SUNDAY2': 'CLOSED',
                         'LINK': 'https://nudining.com/hours'}
CAFE_CROSSING_SPRING_BREAK = {'FRIDAY': [7, '00', 16, '00'],
                              'SATURDAY': 'CLOSED',
                              'SUNDAY': 'CLOSED',
                              'MONDAY-THURSDAY': [7, '00', 16, '00'],
                              'FRIDAY2': [7, '00', 15, '00'],
                              'SATURDAY2': 'CLOSED',
                              'SUNDAY2': 'CLOSED',
                              'LINK': 'https://nudining.com/hours'}
FACULTY_CLUB_SPRING_BREAK = {'FRIDAY': [11, '30', 14, '00'],
                             'SATURDAY': 'CLOSED',
                             'SUNDAY': 'CLOSED',
                             'MONDAY-THURSDAY': [11, '30', 14, '00'],
                             'FRIDAY2': [11, '30', 14, '00'],
                             'SATURDAY2': 'CLOSED',
                             'SUNDAY2': 'CLOSED',
                             'LINK': 'https://nudining.com/hours'}
KIGO_SPRING_BREAK = {'FRIDAY': [11, '00', 15, '00'],
                     'SATURDAY': 'CLOSED',
                     'SUNDAY': 'CLOSED',
                     'MONDAY-THURSDAY': 'CLOSED',
                     'FRIDAY2': 'CLOSED',
                     'SATURDAY2': 'CLOSED',
                     'SUNDAY2': 'CLOSED',
                     'LINK': 'https://nudining.com/hours'}
THE_MARKET_SPRING_BREAK = {'FRIDAY': [7, '00', 21, '00'],
                           'SATURDAY': [10, '00', 19, '00'],
                           'SUNDAY': [10, '00', 19, '00'],
                           'MONDAY-THURSDAY': [7, '00', 20, '00'],
                           'FRIDAY2': [7, '00', 20, '00'],
                           'SATURDAY2': [10, '00', 19, '00'],
                           'SUNDAY2': [11, '00', 20, '00'],
                           'LINK': 'https://nudining.com/hours'}
POPEYES_SPRING_BREAK = {'FRIDAY': [10, '30', 20, '00'],
                        'SATURDAY': [11, '00', 17, '00'],
                        'SUNDAY': [12, '00', 17, '00'],
                        'MONDAY-THURSDAY': [10, '30', 18, '00'],
                        'FRIDAY2': [10, '30', 18, '00'],
                        'SATURDAY2': [11, '00', 17, '00'],
                        'SUNDAY2': [12, '00', 19, '00'],
                        'LINK': 'https://nudining.com/hours'}
REBECCAS_SPRING_BREAK = {'FRIDAY': [7, '00', 16, '00'],
                         'SATURDAY': 'CLOSED',
                         'SUNDAY': 'CLOSED',
                         'MONDAY-THURSDAY': [7, '00', 14, '00'],
                         'FRIDAY2': [7, '00', 14, '00'],
                         'SATURDAY2': 'CLOSED',
                         'SUNDAY2': 'CLOSED',
                         'LINK': 'https://nudining.com/hours'}
STARBUCKS_SPRING_BREAK = {'FRIDAY': [7, '00', 19, '30'],
                          'SATURDAY': [8, '00', 17, '00'],
                          'SUNDAY': [11, '00', 17, '00'],
                          'MONDAY-THURSDAY': [7, '00', 18, '00'],
                          'FRIDAY2': [7, '00', 18, '00'],
                          'SATURDAY2': [8, '00', 18, '00'],
                          'SUNDAY2': [10, '00', 18, '00'],
                          'LINK': 'https://nudining.com/hours'}
SUBWAY_SPRING_BREAK = {'FRIDAY': [8, '00', 15, '00'],
                       'SATURDAY': 'CLOSED',
                       'SUNDAY': 'CLOSED',
                       'MONDAY-THURSDAY': 'CLOSED',
                       'FRIDAY2': 'CLOSED',
                       'SATURDAY2': 'CLOSED',
                       'SUNDAY2': 'CLOSED',
                       'LINK': 'https://nudining.com/hours'}
SWEET_TOMATOES_SPRING_BREAK = {'FRIDAY': [11, '00', 15, '00'],
                               'SATURDAY': 'CLOSED',
                               'SUNDAY': 'CLOSED',
                               'MONDAY-THURSDAY': 'CLOSED',
                               'FRIDAY2': 'CLOSED',
                               'SATURDAY2': 'CLOSED',
                               'SUNDAY2': 'CLOSED',
                               'LINK': 'https://nudining.com/hours'}
THE_WEST_END_SPRING_BREAK = {'FRIDAY': [11, '00', 14, '00'],
                             'SATURDAY': 'CLOSED',
                             'SUNDAY': 'CLOSED',
                             'MONDAY-THURSDAY': 'CLOSED',
                             'FRIDAY2': 'CLOSED',
                             'SATURDAY2': 'CLOSED',
                             'SUNDAY2': 'CLOSED',
                             'LINK': 'https://nudining.com/hours'}
UBURGER_SPRING_BREAK = {'FRIDAY': [11, '00', 18, '00'],
                        'SATURDAY': 'CLOSED',
                        'SUNDAY': 'CLOSED',
                        'MONDAY-THURSDAY': [11, '00', 16, '00'],
                        'FRIDAY2': [11, '00', 16, '00'],
                        'SATURDAY2': 'CLOSED',
                        'SUNDAY2': [12, '00', 18, '00'],
                        'LINK': 'https://nudining.com/hours'}
ZATAR_SPRING_BREAK = {'FRIDAY': [11, '00', 14, '00'],
                      'SATURDAY': 'CLOSED',
                      'SUNDAY': 'CLOSED',
                      'MONDAY-THURSDAY': 'CLOSED',
                      'FRIDAY2': 'CLOSED',
                      'SATURDAY2': 'CLOSED',
                      'SUNDAY2': 'CLOSED',
                      'LINK': 'https://nudining.com/hours'}

SPRING_BREAK_LOCATIONS = {('INTERNATIONAL VILLAGE', 'IV'): IV_SPRING_BREAK, ('STETSON EAST', 'STEAST', 'STETSON E'): STEAST_SPRING_BREAK,
                          ('STETSON WEST', 'STWEST', 'STETSON W'): STWEST_SPRING_BREAK, ('OUTTAKES', 'OUTTAKES'): OUTTAKES_SPRING_BREAK,
                          ('ARGO TEA', 'ARGO'): ARGO_TEA_SPRING_BREAK, ('CAFÉ 716', 'CAFE 716'): CAFE_716_SPRING_BREAK,
                          ('CAFÉ CROSSING', 'CAFE CROSSING', 'CAFE CROSS'): CAFE_CROSSING_SPRING_BREAK,
                          ('FACULTY CLUB', 'FACULTY CLUB'): FACULTY_CLUB_SPRING_BREAK, ('KIGO KITCHEN', 'KIGO', 'KIGOS'): KIGO_SPRING_BREAK,
                          ('THE MARKET', 'MARKET'): THE_MARKET_SPRING_BREAK,
                          ('POPEYES LOUISIANA KITCHEN', 'POPEYES KITCHEN', 'POPEYES'): POPEYES_SPRING_BREAK,
                          ("REBECCA'S", 'REBECCAS'): REBECCAS_SPRING_BREAK, ('STARBUCKS', 'STARBUCKS'): STARBUCKS_SPRING_BREAK,
                          ('SUBWAY', 'SUBWAY'): SUBWAY_SPRING_BREAK, ('SWEET TOMATOES', 'SWEET TOMATOES'): SWEET_TOMATOES_SPRING_BREAK,
                          ('THE WEST END', 'WEST END'): THE_WEST_END_SPRING_BREAK, ('UBURGER', 'UBURGERS'): UBURGER_SPRING_BREAK,
                          ("ZA'TAR", 'ZATAR'): ZATAR_SPRING_BREAK}

# Patriot's Day Hours (April 11-17, 2019)
IV_PATRIOTS_DAY = {'THURSDAY': [7, '00', 20, '00'],
                   'FRIDAY': [7, '00', 21, '00'],
                   'SATURDAY': [8, '00', 21, '00'],
                   'SUNDAY': [8, '00', 21, '00'],
                   'MONDAY': [8, '00', 21, '00'],
                   'TUESDAY-WEDNESDAY': [7, '00', 22, '00'],
                   'LINK': 'https://nudining.com/hours'}
STEAST_PATRIOTS_DAY = {'THURSDAY': [7, '00', 23, '00'],
                       'FRIDAY': [7, '00', 21, '00'],
                       'SATURDAY': [8, '00', 21, '00'],
                       'SUNDAY': [8, '00', 21, '00'],
                       'MONDAY': [8, '00', 22, '00'],
                       'TUESDAY-WEDNESDAY': [7, '00', 23, '00'],
                       'LINK': 'https://nudining.com/hours'}
STWEST_PATRIOTS_DAY = {'THURSDAY': [11, '00', 8, '00'],
                       'FRIDAY': 'CLOSED',
                       'SATURDAY': 'CLOSED',
                       'SUNDAY': 'CLOSED',
                       'MONDAY': [4, '00', 20, '00'],
                       'TUESDAY-WEDNESDAY': [11, '00', 20, '00'],
                       'LINK': 'https://nudining.com/hours'}
OUTTAKES_PATRIOTS_DAY = {'THURSDAY': [11, '00', 1, '00'],
                         'FRIDAY': [11, '00', 19, '00'],
                         'SATURDAY': 'CLOSED',
                         'SUNDAY': 'CLOSED',
                         'MONDAY': 'CLOSED',
                         'TUESDAY-WEDNESDAY': [11, '00', 25, '00'],
                         'LINK': 'https://nudining.com/hours'}
ARGO_TEA_PATRIOTS_DAY = {'THURSDAY': [7, '30', 20, '00'],
                         'FRIDAY': [7, '30', 16, '00'],
                         'SATURDAY': 'CLOSED',
                         'SUNDAY': 'CLOSED',
                         'MONDAY': 'CLOSED',
                         'TUESDAY-WEDNESDAY': [7, '30', 20, '00'],
                         'LINK': 'https://nudining.com/hours'}
CAFE_716_PATRIOTS_DAY = {'THURSDAY': [7, '00', 16, '00'],
                         'FRIDAY': [7, '00', 15, '00'],
                         'SATURDAY': 'CLOSED',
                         'SUNDAY': 'CLOSED',
                         'MONDAY': 'CLOSED',
                         'TUESDAY-WEDNESDAY': [7, '00', 16, '00'],
                         'LINK': 'https://nudining.com/hours'}
CAFE_CROSSING_PATRIOTS_DAY = {'THURSDAY': [7, '00', 17, '00'],
                              'FRIDAY': [7, '30', 16, '00'],
                              'SATURDAY': 'CLOSED',
                              'SUNDAY': 'CLOSED',
                              'MONDAY': 'CLOSED',
                              'TUESDAY-WEDNESDAY': [7, '00', 17, '00'],
                              'LINK': 'https://nudining.com/hours'}
FACULTY_CLUB_PATRIOTS_DAY = {'THURSDAY': [11, '30', 14, '00'],
                             'FRIDAY': [11, '30', 14, '00'],
                             'SATURDAY': 'CLOSED',
                             'SUNDAY': 'CLOSED',
                             'MONDAY': 'CLOSED',
                             'TUESDAY-WEDNESDAY': [11, '30', 14, '00'],
                             'LINK': 'https://nudining.com/hours'}
KIGO_PATRIOTS_DAY = {'THURSDAY': [11, '00', 19, '00'],
                     'FRIDAY': [11, '00', 15, '00'],
                     'SATURDAY': 'CLOSED',
                     'SUNDAY': 'CLOSED',
                     'MONDAY': 'CLOSED',
                     'TUESDAY-WEDNESDAY': [11, '00', 19, '00'],
                     'LINK': 'https://nudining.com/hours'}
THE_MARKET_PATRIOTS_DAY = {'THURSDAY': [7, '00', 22, '00'],
                           'FRIDAY': [7, '00', 21, '30'],
                           'SATURDAY': [9, '00', 21, '00'],
                           'SUNDAY': [11, '00', 20, '00'],
                           'MONDAY': [10, '00', 21, '00'],
                           'TUESDAY-WEDNESDAY': [7, '00', 22, '00'],
                           'LINK': 'https://nudining.com/hours'}
POPEYES_PATRIOTS_DAY = {'THURSDAY': [7, '00', 20, '00'],
                        'FRIDAY': [7, '00', 21, '00'],
                        'SATURDAY': [8, '00', 21, '00'],
                        'SUNDAY': [8, '00', 21, '00'],
                        'MONDAY': [8, '00', 21, '00'],
                        'TUESDAY-WEDNESDAY': [7, '00', 22, '00'],
                        'LINK': 'https://nudining.com/hours'}
REBECCAS_PATRIOTS_DAY = {'THURSDAY': [7, '00', 16, '00'],
                         'FRIDAY': [7, '00', 16, '00'],
                         'SATURDAY': 'CLOSED',
                         'SUNDAY': 'CLOSED',
                         'MONDAY': [7, '00', 14, '00'],
                         'TUESDAY-WEDNESDAY': [7, '00', 16, '00'],
                         'LINK': 'https://nudining.com/hours'}
STARBUCKS_PATRIOTS_DAY = {'THURSDAY': [7, '00', 21, '00'],
                          'FRIDAY': [7, '00', 21, '00'],
                          'SATURDAY': [8, '00', 21, '00'],
                          'SUNDAY': [11, '00', 17, '00'],
                          'MONDAY': [9, '00', 21, '00'],
                          'TUESDAY-WEDNESDAY': [7, '00', 21, '00'],
                          'LINK': 'https://nudining.com/hours'}
SUBWAY_PATRIOTS_DAY = {'THURSDAY': [8, '00', 20, '30'],
                       'FRIDAY': [8, '00', 16, '00'],
                       'SATURDAY': 'CLOSED',
                       'SUNDAY': 'CLOSED',
                       'MONDAY': 'CLOSED',
                       'TUESDAY-WEDNESDAY': [7, '00', 22, '30'],
                       'LINK': 'https://nudining.com/hours'}
SWEET_TOMATOES_PATRIOTS_DAY = {'THURSDAY': [11, '00', 19, '00'],
                               'FRIDAY': [11, '00', 18, '00'],
                               'SATURDAY': 'CLOSED',
                               'SUNDAY': 'CLOSED',
                               'MONDAY': 'CLOSED',
                               'TUESDAY-WEDNESDAY': [11, '00', 19, '00'],
                               'LINK': 'https://nudining.com/hours'}
THE_WEST_END_PATRIOTS_DAY = {'THURSDAY': [11, '00', 15, '00'],
                             'FRIDAY': [7, '00', 21, '00'],
                             'SATURDAY': 'CLOSED',
                             'SUNDAY': 'CLOSED',
                             'MONDAY': 'CLOSED',
                             'TUESDAY-WEDNESDAY': [11, '00', 19, '00'],
                             'LINK': 'https://nudining.com/hours'}
UBURGER_PATRIOTS_DAY = {'THURSDAY': [11, '00', 20, '00'],
                        'FRIDAY': [11, '00', 20, '00'],
                        'SATURDAY': [11, '00', 15, '00'],
                        'SUNDAY': 'CLOSED',
                        'MONDAY': [11, '00', 19, '00'],
                        'TUESDAY-WEDNESDAY': [11, '00', 20, '00'],
                        'LINK': 'https://nudining.com/hours'}

PATRIOTS_DAY_LOCATIONS = {('INTERNATIONAL VILLAGE', 'IV'): IV_PATRIOTS_DAY, ('STETSON EAST', 'STEAST', 'STETSON E'): STEAST_PATRIOTS_DAY,
                          ('STETSON WEST', 'STWEST', 'STETSON W'): STWEST_PATRIOTS_DAY, ('OUTTAKES', 'OUTTAKES'): OUTTAKES_PATRIOTS_DAY,
                          ('ARGO TEA', 'ARGO'): ARGO_TEA_PATRIOTS_DAY, ('CAFÉ 716', 'CAFE 716'): CAFE_716_PATRIOTS_DAY,
                          ('CAFÉ CROSSING', 'CAFE CROSSING', 'CAFE CROSS'): CAFE_CROSSING_PATRIOTS_DAY,
                          ('FACULTY CLUB', 'FACULTY CLUB'): FACULTY_CLUB_PATRIOTS_DAY, ('KIGO KITCHEN', 'KIGO', 'KIGOS'): KIGO_PATRIOTS_DAY,
                          ('THE MARKET', 'MARKET'): THE_MARKET_PATRIOTS_DAY,
                          ('POPEYES LOUISIANA KITCHEN', 'POPEYES KITCHEN', 'POPEYES'): POPEYES_PATRIOTS_DAY,
                          ("REBECCA'S", 'REBECCAS'): REBECCAS_PATRIOTS_DAY, ('STARBUCKS', 'STARBUCKS'): STARBUCKS_PATRIOTS_DAY,
                          ('SUBWAY', 'SUBWAY'): SUBWAY_PATRIOTS_DAY, ('SWEET TOMATOES', 'SWEET TOMATOES'): SWEET_TOMATOES_PATRIOTS_DAY,
                          ('THE WEST END', 'WEST END'): THE_WEST_END_PATRIOTS_DAY, ('UBURGER', 'UBURGERS'): UBURGER_PATRIOTS_DAY}

# Finals Weeks 2019 Hours (April 18-26, 2019)
IV_FINALS_WEEK = {'THURSDAY': [7, '00', 22, '00'],
                  'FRIDAY': [7, '00', 21, '00'],
                  'SATURDAY': [8, '00', 21, '00'],
                  'SUNDAY': [8, '00', 21, '00'],
                  'MONDAY-TUESDAY': [7, '00', 22, '00'],
                  'WEDNESDAY': [7, '00', 22, '00'],
                  'THURSDAY2': [7, '00', 22, '00'],
                  'FRIDAY2': [7, '00', 21, '00'],
                  'LINK': 'https://nudining.com/hours'}
STEAST_FINALS_WEEK = {'THURSDAY': [7, '00', 23, '00'],
                      'FRIDAY': [7, '00', 22, '00'],
                      'SATURDAY': [8, '00', 22, '00'],
                      'SUNDAY': [8, '00', 22, '00'],
                      'MONDAY-TUESDAY': [7, '00', 23, '00'],
                      'WEDNESDAY': [7, '00', 23, '00'],
                      'THURSDAY2': [7, '00', 23, '00'],
                      'FRIDAY2': [7, '00', 15, '00'],
                      'LINK': 'https://nudining.com/hours'}
STWEST_FINALS_WEEK = {'THURSDAY': [11, '00', 20, '00'],
                      'FRIDAY': [11, '00', 17, '00'],
                      'SATURDAY': 'CLOSED',
                      'SUNDAY': [16, '00', 20, '00'],
                      'MONDAY-TUESDAY': [11, '00', 20, '00'],
                      'WEDNESDAY': [11, '00', 20, '00'],
                      'THURSDAY2': [11, '00', 16, '00'],
                      'FRIDAY2': 'CLOSED',
                      'LINK': 'https://nudining.com/hours'}
OUTTAKES_FINALS_WEEK = {'THURSDAY': [11, '00', 13, '00'],
                        'FRIDAY': [11, '00', 20, '00'],
                        'SATURDAY': [12, '00', 18, '00'],
                        'SUNDAY': 'CLOSED',
                        'MONDAY-TUESDAY': [11, '00', 25, '00'],
                        'WEDNESDAY': [11, '00', 25, '00'],
                        'THURSDAY2': [11, '00', 16, '00'],
                        'FRIDAY2': 'CLOSED',
                        'LINK': 'https://nudining.com/hours'}
ARGO_TEA_FINALS_WEEK = {'THURSDAY': [7, '30', 22, '00'],
                        'FRIDAY': [7, '30', 17, '00'],
                        'SATURDAY': 'CLOSED',
                        'SUNDAY': [13, '00', 22, '00'],
                        'MONDAY-TUESDAY': [7, '30', 22, '00'],
                        'WEDNESDAY': [7, '30', 19, '00'],
                        'THURSDAY2': [7, '30', 19, '00'],
                        'FRIDAY2': [7, '30', 15, '00'],
                        'LINK': 'https://nudining.com/hours'}
CAFE_716_FINALS_WEEK = {'THURSDAY': [7, '00', 16, '00'],
                        'FRIDAY': [7, '00', 15, '00'],
                        'SATURDAY': 'CLOSED',
                        'SUNDAY': 'CLOSED',
                        'MONDAY-TUESDAY': [7, '00', 16, '00'],
                        'WEDNESDAY': [7, '00', 16, '00'],
                        'THURSDAY2': [7, '00', 16, '00'],
                        'FRIDAY2': [7, '00', 15, '00'],
                        'LINK': 'https://nudining.com/hours'}
CAFE_CROSSING_FINALS_WEEK = {'THURSDAY': [7, '00', 17, '00'],
                             'FRIDAY': [7, '00', 16, '00'],
                             'SATURDAY': 'CLOSED',
                             'SUNDAY': 'CLOSED',
                             'MONDAY-TUESDAY': [7, '00', 17, '00'],
                             'WEDNESDAY': [7, '00', 17, '00'],
                             'THURSDAY2': [7, '00', 17, '00'],
                             'FRIDAY2': [7, '00', 16, '00'],
                             'LINK': 'https://nudining.com/hours'}
FACULTY_CLUB_FINALS_WEEK = {'THURSDAY': [11, '30', 14, '00'],
                            'FRIDAY': [11, '30', 14, '00'],
                            'SATURDAY': 'CLOSED',
                            'SUNDAY': 'CLOSED',
                            'MONDAY-TUESDAY': [11, '30', 14, '00'],
                            'WEDNESDAY': [11, '30', 14, '00'],
                            'THURSDAY2': [11, '30', 14, '00'],
                            'FRIDAY2': [11, '30', 14, '00'],
                            'LINK': 'https://nudining.com/hours'}
KIGO_FINALS_WEEK = {'THURSDAY': [11, '00', 19, '00'],
                    'FRIDAY': [11, '00', 16, '00'],
                    'SATURDAY': 'CLOSED',
                    'SUNDAY': 'CLOSED',
                    'MONDAY-TUESDAY': [11, '00', 19, '00'],
                    'WEDNESDAY': [11, '00', 19, '00'],
                    'THURSDAY2': [11, '00', 19, '00'],
                    'FRIDAY2': [11, '00', 15, '00'],
                    'LINK': 'https://nudining.com/hours'}
THE_MARKET_FINALS_WEEK = {'THURSDAY': [7, '00', 22, '00'],
                          'FRIDAY': [7, '00', 21, '30'],
                          'SATURDAY': [9, '00', 21, '00'],
                          'SUNDAY': [11, '00', 23, '30'],
                          'MONDAY-TUESDAY': [7, '00', 23, '00'],
                          'WEDNESDAY': [7, '00', 23, '00'],
                          'THURSDAY2': [7, '00', 23, '00'],
                          'FRIDAY2': [7, '00', 18, '00'],
                          'LINK': 'https://nudining.com/hours'}
POPEYES_FINALS_WEEK = {'THURSDAY': [10, '30', 21, '00'],
                       'FRIDAY': [10, '30', 21, '30'],
                       'SATURDAY': [10, '30', 20, '00'],
                       'SUNDAY': [12, '00', 19, '30'],
                       'MONDAY-TUESDAY': [10, '30', 21, '00'],
                       'WEDNESDAY': [10, '30', 21, '00'],
                       'THURSDAY2': [10, '30', 21, '00'],
                       'FRIDAY2': [10, '30', 17, '00'],
                       'LINK': 'https://nudining.com/hours'}
REBECCAS_FINALS_WEEK = {'THURSDAY': [7, '00', 16, '00'],
                        'FRIDAY': [7, '00', 16, '00'],
                        'SATURDAY': 'CLOSED',
                        'SUNDAY': 'CLOSED',
                        'MONDAY-TUESDAY': [7, '00', 16, '00'],
                        'WEDNESDAY': [7, '00', 16, '00'],
                        'THURSDAY2': [7, '00', 16, '00'],
                        'FRIDAY2': [7, '00', 16, '00'],
                        'LINK': 'https://nudining.com/hours'}
STARBUCKS_FINALS_WEEK = {'THURSDAY': [7, '00', 23, '00'],
                         'FRIDAY': [7, '00', 22, '00'],
                         'SATURDAY': [8, '00', 21, '00'],
                         'SUNDAY': [10, '00', 23, '30'],
                         'MONDAY-TUESDAY': [7, '00', 23, '30'],
                         'WEDNESDAY': [7, '00', 23, '00'],
                         'THURSDAY2': [7, '00', 23, '00'],
                         'FRIDAY2': [7, '00', 17, '00'],
                         'LINK': 'https://nudining.com/hours'}
SUBWAY_FINALS_WEEK = {'THURSDAY': [8, '00', 20, '30'],
                      'FRIDAY': [8, '00', 16, '00'],
                      'SATURDAY': 'CLOSED',
                      'SUNDAY': 'CLOSED',
                      'MONDAY-TUESDAY': [8, '00', 20, '30'],
                      'WEDNESDAY': [8, '00', 18, '00'],
                      'THURSDAY2': [8, '00', 18, '00'],
                      'FRIDAY2': [8, '00', 15, '00'],
                      'LINK': 'https://nudining.com/hours'}
SWEET_TOMATOES_FINALS_WEEK = {'THURSDAY': [11, '00', 19, '00'],
                              'FRIDAY': [11, '00', 18, '00'],
                              'SATURDAY': 'CLOSED',
                              'SUNDAY': 'CLOSED',
                              'MONDAY-TUESDAY': [11, '00', 19, '00'],
                              'WEDNESDAY': [11, '00', 19, '00'],
                              'THURSDAY2': [11, '00', 19, '00'],
                              'FRIDAY2': 'CLOSED',
                              'LINK': 'https://nudining.com/hours'}
THE_WEST_END_FINALS_WEEK = {'THURSDAY': [11, '00', 19, '30'],
                            'FRIDAY': [11, '00', 15, '00'],
                            'SATURDAY': 'CLOSED',
                            'SUNDAY': 'CLOSED',
                            'MONDAY-TUESDAY': [11, '00', 19, '30'],
                            'WEDNESDAY': [11, '00', 15, '00'],
                            'THURSDAY2': [11, '00', 15, '00'],
                            'FRIDAY2': 'CLOSED',
                            'LINK': 'https://nudining.com/hours'}
UBURGER_FINALS_WEEK = {'THURSDAY': [11, '00', 20, '00'],
                       'FRIDAY': [11, '00', 20, '00'],
                       'SATURDAY': [11, '00', 19, '00'],
                       'SUNDAY': [12, '00', 19, '00'],
                       'MONDAY-TUESDAY': [11, '00', 20, '00'],
                       'WEDNESDAY': [11, '00', 20, '00'],
                       'THURSDAY2': [11, '00', 20, '00'],
                       'FRIDAY2': [11, '00', 17, '00'],
                       'LINK': 'https://nudining.com/hours'}

FINALS_WEEK_LOCATIONS = {('INTERNATIONAL VILLAGE', 'IV'): IV_FINALS_WEEK, ('STETSON EAST', 'STEAST', 'STETSON E'): STEAST_FINALS_WEEK,
                         ('STETSON WEST', 'STWEST', 'STETSON W'): STWEST_FINALS_WEEK, ('OUTTAKES', 'OUTTAKES'): OUTTAKES_FINALS_WEEK,
                         ('ARGO TEA', 'ARGO'): ARGO_TEA_FINALS_WEEK, ('CAFÉ 716', 'CAFE 716'): CAFE_716_FINALS_WEEK,
                         ('CAFÉ CROSSING', 'CAFE CROSSING', 'CAFE CROSS'): CAFE_CROSSING_FINALS_WEEK,
                         ('FACULTY CLUB', 'FACULTY CLUB'): FACULTY_CLUB_FINALS_WEEK, ('KIGO KITCHEN', 'KIGO', 'KIGOS'): KIGO_FINALS_WEEK,
                         ('THE MARKET', 'MARKET'): THE_MARKET_FINALS_WEEK,
                         ('POPEYES LOUISIANA KITCHEN', 'POPEYES KITCHEN', 'POPEYES'): POPEYES_FINALS_WEEK,
                         ("REBECCA'S", 'REBECCAS'): REBECCAS_FINALS_WEEK, ('STARBUCKS', 'STARBUCKS'): STARBUCKS_FINALS_WEEK,
                         ('SUBWAY', 'SUBWAY'): SUBWAY_FINALS_WEEK, ('SWEET TOMATOES', 'SWEET TOMATOES'): SWEET_TOMATOES_FINALS_WEEK,
                         ('THE WEST END', 'WEST END'): THE_WEST_END_FINALS_WEEK, ('UBURGER', 'UBURGERS'): UBURGER_FINALS_WEEK}

# Senior Week 2019 Hours (April 27-May 5, 2019)
IV_SENIOR_WEEK = {'SATURDAY': [8, '00', 20, '00'],
                  'SUNDAY': [8, '00', 20, '00'],
                  'MONDAY-WEDNESDAY': [7, '00', 21, '00'],
                  'THURSDAY': [7, '00', 21, '00'],
                  'FRIDAY': [7, '00', 20, '00'],
                  'SATURDAY & SUNDAY': [8, '00', 20, '00'],
                  'LINK': 'https://nudining.com/hours'}
STEAST_SENIOR_WEEK = {'SATURDAY': 'CLOSED',
                      'SUNDAY': 'CLOSED',
                      'MONDAY-WEDNESDAY': 'CLOSED',
                      'THURSDAY': 'CLOSED',
                      'FRIDAY': 'CLOSED',
                      'SATURDAY & SUNDAY': 'CLOSED',
                      'LINK': 'https://nudining.com/hours'}
STWEST_SENIOR_WEEK = {'SATURDAY': 'CLOSED',
                      'SUNDAY': 'CLOSED',
                      'MONDAY-WEDNESDAY': 'CLOSED',
                      'THURSDAY': 'CLOSED',
                      'FRIDAY': 'CLOSED',
                      'SATURDAY & SUNDAY': 'CLOSED',
                      'LINK': 'https://nudining.com/hours'}
OUTTAKES_SENIOR_WEEK = {'SATURDAY': 'CLOSED',
                        'SUNDAY': 'CLOSED',
                        'MONDAY-WEDNESDAY': 'CLOSED',
                        'THURSDAY': 'CLOSED',
                        'FRIDAY': 'CLOSED',
                        'SATURDAY & SUNDAY': 'CLOSED',
                        'LINK': 'https://nudining.com/hours'}
ARGO_TEA_SENIOR_WEEK = {'SATURDAY': 'CLOSED',
                        'SUNDAY': 'CLOSED',
                        'MONDAY-WEDNESDAY': 'CLOSED',
                        'THURSDAY': 'CLOSED',
                        'FRIDAY': 'CLOSED',
                        'SATURDAY & SUNDAY': 'CLOSED',
                        'LINK': 'https://nudining.com/hours'}
CAFE_CROSSING_SENIOR_WEEK = {'SATURDAY': 'CLOSED',
                             'SUNDAY': 'CLOSED',
                             'MONDAY-WEDNESDAY': [7, '00', 16, '00'],
                             'THURSDAY': [7, '00', 16, '00'],
                             'FRIDAY': [7, '00', 15, '00'],
                             'SATURDAY & SUNDAY': 'CLOSED',
                             'LINK': 'https://nudining.com/hours'}
CAFE_716_SENIOR_WEEK = {'SATURDAY': 'CLOSED',
                        'SUNDAY': 'CLOSED',
                        'MONDAY-WEDNESDAY': [7, '00', 15, '00'],
                        'THURSDAY': [7, '00', 15, '00'],
                        'FRIDAY': [7, '00', 14, '00'],
                        'SATURDAY & SUNDAY': 'CLOSED',
                        'LINK': 'https://nudining.com/hours'}
FACULTY_CLUB_SENIOR_WEEK = {'SATURDAY': 'CLOSED',
                            'SUNDAY': 'CLOSED',
                            'MONDAY-WEDNESDAY': [11, '30', 14, '00'],
                            'THURSDAY': [11, '30', 14, '00'],
                            'FRIDAY': [11, '30', 14, '00'],
                            'SATURDAY & SUNDAY': 'CLOSED',
                            'LINK': 'https://nudining.com/hours'}
KIGO_SENIOR_WEEK = {'SATURDAY': 'CLOSED',
                    'SUNDAY': 'CLOSED',
                    'MONDAY-WEDNESDAY': 'CLOSED',
                    'THURSDAY': 'CLOSED',
                    'FRIDAY': 'CLOSED',
                    'SATURDAY & SUNDAY': 'CLOSED',
                    'LINK': 'https://nudining.com/hours'}
POPEYES_SENIOR_WEEK = {'SATURDAY': 'CLOSED',
                       'SUNDAY': 'CLOSED',
                       'MONDAY-WEDNESDAY': [10, '30', 17, '30'],
                       'THURSDAY': [10, '30', 17, '30'],
                       'FRIDAY': [10, '30', 15, '00'],
                       'SATURDAY & SUNDAY': 'CLOSED',
                       'LINK': 'https://nudining.com/hours'}
REBECCAS_SENIOR_WEEK = {'SATURDAY': 'CLOSED',
                        'SUNDAY': 'CLOSED',
                        'MONDAY-WEDNESDAY': [7, '00', 15, '00'],
                        'THURSDAY': [7, '00', 15, '00'],
                        'FRIDAY': [7, '00', 15, '00'],
                        'SATURDAY & SUNDAY': 'CLOSED',
                        'LINK': 'https://nudining.com/hours'}
STARBUCKS_SENIOR_WEEK = {'SATURDAY': 'CLOSED',
                         'SUNDAY': 'CLOSED',
                         'MONDAY-WEDNESDAY': [7, '00', 17, '00'],
                         'THURSDAY': [7, '00', 17, '00'],
                         'FRIDAY': [8, '00', 15, '00'],
                         'SATURDAY & SUNDAY': 'CLOSED',
                         'LINK': 'https://nudining.com/hours'}
SUBWAY_SENIOR_WEEK = {'SATURDAY': 'CLOSED',
                      'SUNDAY': 'CLOSED',
                      'MONDAY-WEDNESDAY': [10, '00', 14, '00'],
                      'THURSDAY': 'CLOSED',
                      'FRIDAY': 'CLOSED',
                      'SATURDAY & SUNDAY': 'CLOSED',
                      'LINK': 'https://nudining.com/hours'}
SWEET_TOMATOES_SENIOR_WEEK = {'SATURDAY': 'CLOSED',
                              'SUNDAY': 'CLOSED',
                              'MONDAY-WEDNESDAY': [11, '00', 15, '00'],
                              'THURSDAY': [11, '00', 15, '00'],
                              'FRIDAY': 'CLOSED',
                              'SATURDAY & SUNDAY': 'CLOSED',
                              'LINK': 'https://nudining.com/hours'}
THE_MARKET_SENIOR_WEEK = {'SATURDAY': 'CLOSED',
                          'SUNDAY': 'CLOSED',
                          'MONDAY-WEDNESDAY': [7, '00', 18, '00'],
                          'THURSDAY': [7, '00', 18, '00'],
                          'FRIDAY': [8, '00', 16, '00'],
                          'SATURDAY & SUNDAY': 'CLOSED',
                          'LINK': 'https://nudining.com/hours'}
THE_WEST_END_SENIOR_WEEK = {'SATURDAY': 'CLOSED',
                            'SUNDAY': 'CLOSED',
                            'MONDAY-WEDNESDAY': 'CLOSED',
                            'THURSDAY': 'CLOSED',
                            'FRIDAY': 'CLOSED',
                            'SATURDAY & SUNDAY': 'CLOSED',
                            'LINK': 'https://nudining.com/hours'}
UBURGER_SENIOR_WEEK = {'SATURDAY': 'CLOSED',
                       'SUNDAY': 'CLOSED',
                       'MONDAY-WEDNESDAY': [11, '00', 17, '00'],
                       'THURSDAY': [11, '00', 17, '00'],
                       'FRIDAY': 'CLOSED',
                       'SATURDAY & SUNDAY': 'CLOSED',
                       'LINK': 'https://nudining.com/hours'}

SENIOR_WEEK_LOCATIONS = {('INTERNATIONAL VILLAGE', 'IV'): IV_SENIOR_WEEK, ('STETSON EAST', 'STEAST', 'STETSON E'): STEAST_SENIOR_WEEK,
                         ('STETSON WEST', 'STWEST', 'STETSON W'): STWEST_SENIOR_WEEK, ('OUTTAKES', 'OUTTAKES'): OUTTAKES_SENIOR_WEEK,
                         ('ARGO TEA', 'ARGO'): ARGO_TEA_SENIOR_WEEK, ('CAFÉ 716', 'CAFE 716'): CAFE_716_SENIOR_WEEK,
                         ('CAFÉ CROSSING', 'CAFE CROSSING', 'CAFE CROSS'): CAFE_CROSSING_SENIOR_WEEK,
                         ('FACULTY CLUB', 'FACULTY CLUB'): FACULTY_CLUB_SENIOR_WEEK, ('KIGO KITCHEN', 'KIGO', 'KIGOS'): KIGO_SENIOR_WEEK,
                         ('POPEYES LOUISIANA KITCHEN', 'POPEYES KITCHEN', 'POPEYES'): POPEYES_SENIOR_WEEK,
                         ("REBECCA'S", 'REBECCAS'): REBECCAS_SENIOR_WEEK, ('STARBUCKS', 'STARBUCKS'): STARBUCKS_SENIOR_WEEK,
                         ('SUBWAY', 'SUBWAY'): SUBWAY_SENIOR_WEEK, ('SWEET TOMATOES', 'SWEET TOMATOES'): SWEET_TOMATOES_SENIOR_WEEK,
                         ('THE MARKET', 'MARKET'): THE_MARKET_SENIOR_WEEK, ('THE WEST END', 'WEST END'): THE_WEST_END_SENIOR_WEEK,
                         ('UBURGER', 'UBURGERS'): UBURGER_SENIOR_WEEK}

# Summer 1 2019 Hours (Maay 6-June 25, 2019)
IV_SUMMER1 = {'MONDAY-THURSDAY': [7, '00', 21, '00'],
              'FRIDAY': [7, '00', 20, '00'],
              'WEEKENDS': [8, '00', 20, '00'],
              'LINK': 'https://nudining.com/hours'}
STEAST_SUMMER1 = {'EVERYDAY': 'CLOSED',
                  'LINK': 'https://nudining.com/hours'}
STWEST_SUMMER1 = {'EVERYDAY': 'CLOSED',
                  'LINK': 'https://nudining.com/hours'}
OUTTAKES_SUMMER1 = {'EVERYDAY': 'CLOSED',
                    'LINK': 'https://nudining.com/hours'}
ARGO_TEA_SUMMER1 = {'EVERYDAY': 'CLOSED',
                    'LINK': 'https://nudining.com/hours'}
CAFE_CROSSING_SUMMER1 = {'MONDAY-THURSDAY': [7, '00', 16, '00'],
                         'FRIDAY': [7, '00', 15, '00'],
                         'WEEKENDS': 'CLOSED',
                         'LINK': 'https://nudining.com/hours'}
CAFE_716_SUMMER1 = {'MONDAY-THURSDAY': [7, '00', 16, '00'],
                    'FRIDAY': [7, '00', 15, '00'],
                    'WEEKENDS': 'CLOSED',
                    'LINK': 'https://nudining.com/hours'}
FACULTY_CLUB_SUMMER1 = {'WEEKDAYS': [11, '30', 14, '00'],
                        'WEEKENDS': 'CLOSED',
                        'LINK': 'https://nudining.com/hours'}
KIGO_SUMMER1 = {'MONDAY-THURSDAY': [11, '00', 15, '00'],
                'FRIDAY': [11, '00', 14, '00'],
                'WEEKENDS': 'CLOSED',
                'LINK': 'https://nudining.com/hours'}
POPEYES_SUMMER1 = {'MONDAY-THURSDAY': [10, '30', 18, '30'],
                   'FRIDAY': [10, '30', 17, '30'],
                   'WEEKENDS': 'CLOSED',
                   'LINK': 'https://nudining.com/hours'}
REBECCAS_SUMMER1 = {'MONDAY-THURSDAY': [7, '00', 15, '00'],
                    'FRIDAY': [7, '00', 14, '00'],
                    'WEEKENDS': 'CLOSED',
                    'LINK': 'https://nudining.com/hours'}
STARBUCKS_SUMMER1 = {'MONDAY-THURSDAY': [7, '00', 18, '00'],
                     'FRIDAY': [7, '00', 17, '00'],
                     'WEEKENDS': 'CLOSED',
                     'LINK': 'https://nudining.com/hours'}
SUBWAY_SUMMER1 = {'MONDAY-THURSDAY': [9, '00', 15, '00'],
                  'FRIDAY': 'CLOSED',
                  'WEEKENDS': 'CLOSED',
                  'LINK': 'https://nudining.com/hours'}
SWEET_TOMATOES_SUMMER1 = {'MONDAY-THURSDAY': [11, '30', 15, '00'],
                          'FRIDAY': 'CLOSED',
                          'WEEKENDS': 'CLOSED',
                          'LINK': 'https://nudining.com/hours'}
THE_MARKET_SUMMER1 = {'MONDAY-THURSDAY': [7, '00', 20, '00'],
                      'FRIDAY': [7, '00', 18, '00'],
                      'WEEKENDS': 'CLOSED',
                      'LINK': 'https://nudining.com/hours'}
THE_WEST_END_SUMMER1 = {'MONDAY-THURSDAY': [11, '00', 15, '00'],
                        'FRIDAY': 'CLOSED',
                        'WEEKENDS': 'CLOSED',
                        'LINK': 'https://nudining.com/hours'}
UBURGER_SUMMER1 = {'MONDAY-THURSDAY': [11, '00', 17, '00'],
                   'FRIDAY': [11, '00', 16, '00'],
                   'WEEKENDS': 'CLOSED',
                   'LINK': 'https://nudining.com/hours'}
CHICKEN_LOUS_SUMMER1 = {'WEEKDAYS': [7, '00', 14, '00'],
                        'WEEKENDS': 'CLOSED',
                        'LINK': 'https://www.chickenlous.com'}

SUMMER1_LOCATIONS = {('INTERNATIONAL VILLAGE', 'IV'): IV_SUMMER1, ('STETSON EAST', 'STEAST', 'STETSON E'): STEAST_SUMMER1,
                     ('STETSON WEST', 'STWEST', 'STETSON W'): STWEST_SUMMER1, ('OUTTAKES', 'OUTTAKES'): OUTTAKES_SUMMER1,
                     ('ARGO TEA', 'ARGO'): ARGO_TEA_SUMMER1, ('CAFÉ 716', 'CAFE 716'): CAFE_716_SUMMER1,
                     ('CAFÉ CROSSING', 'CAFE CROSSING', 'CAFE CROSS'): CAFE_CROSSING_SUMMER1,
                     ('FACULTY CLUB', 'FACULTY CLUB'): FACULTY_CLUB_SUMMER1, ('KIGO KITCHEN', 'KIGO', 'KIGOS'): KIGO_SUMMER1,
                     ('POPEYES LOUISIANA KITCHEN', 'POPEYES KITCHEN', 'POPEYES'): POPEYES_SUMMER1,
                     ("REBECCA'S", 'REBECCAS'): REBECCAS_SUMMER1, ('STARBUCKS', 'STARBUCKS'): STARBUCKS_SUMMER1,
                     ('SUBWAY', 'SUBWAY'): SUBWAY_SUMMER1, ('SWEET TOMATOES', 'SWEET TOMATOES'): SWEET_TOMATOES_SUMMER1,
                     ('THE MARKET', 'MARKET'): THE_MARKET_SUMMER1, ('THE WEST END', 'WEST END'): THE_WEST_END_SUMMER1,
                     ('UBURGER', 'UBURGERS'): UBURGER_SUMMER1,
                     ("CHICKEN LOU'S", "CHICKEN LOUS", 'CHICKEN_LOUS', 'CL'): CHICKEN_LOUS_SUMMER1}
